---
title: "git_00"
author: "Jennifer Alvarez"
date: "September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

And cannot pleasures, while they last,  
Be actual unless, when past,  
They leave us shuddering and aghast,  
With anguish smarting?  
And cannot friends be firm and fast,  
And yet bear parting?  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was. 


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make.  
The billows smooth and bright —  
And this was odd, because it was.  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun.  
Had got no business to be there.   
After the day was done —  
"It's very rude of him," she said,  
"To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Behold the rocky wall   
That down its sloping sides   
Pours the swift rain-drops, blending, as they fall,   
In rushing river-tides!   

Yon stream, whose sources run   
Turned by a pebble’s edge,   
Is Athabasca, rolling toward the sun   
Through the cleft mountain-ledge.   

The slender rill had strayed,   
But for the slanting stone,   
To evening’s ocean, with the tangled braid   
Of foam-flecked Oregon.   

So from the heights of Will   
Life’s parting stream descends,   
And, as a moment turns its slender rill,   
Each widening torrent bends,—   

From the same cradle’s side,   
From the same mother’s knee,—   
One to long darkness and the frozen tide,   
One to the Peaceful Sea!  
